[package]
name = "gradient-server"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"
authors = ["Wavelens UG <info@wavelens.io>"]
description = "Nix-based Continuous Integration System"
repository = "https://github.com/wavelens/gradient"

[workspace]
members = [".", "core", "builder", "web", "entity", "migration"]

[dependencies]
builder = { path = "builder" }
clap = { version = "4.5.31", features = ["derive"] }
core = { path = "core" }
tokio = { version = "1.43", features = ["process", "rt-multi-thread"] }
web = { path = "web" }
